-
  branches:
    only:
      - master

  image: Visual Studio 2017
  version: 3.0.3-{branch}-build{build}
  configuration: Release
  
  before_build:
    - nuget restore

  build:
    publish_nuget: true
    verbosity: minimal

  artifacts:
    - path: AsmResolver/bin/Release
      name: Latest stable release

  deploy:
    provider: NuGet
    api_key:
      secure: PVEUaSEahOzJfYurDeVaY8zzkeyuxqL0KlUvgM6cQeldGh2xCvyPeKgEXOOt2ECy
    skip_symbols: false
    artifact: /.*\.nupkg/
-
  branches:
    only:
      - development
  
  image: Visual Studio 2017
  version: 3.0.4-{branch}-build{build}
  configuration: Release

  before_build:
    - nuget restore
    
  build:
    publish_nuget: false
    verbosity: minimal

  artifacts:
    - path: AsmResolver/bin/Release
      name: Bleeding edge

-
  branches:
    only:
      - v4
  
  image: Visual Studio 2019
  version: 4.0.0-alpha-build{build}
  configuration: Release

  skip_commits:
    files:
      - docs/*
      
  before_build:
    - dotnet restore
    
  build:
    publish_nuget: false
    verbosity: minimal

  artifacts:
    - path: src/AsmResolver/bin/Release
      name: alpha-v4
