version: 2.0.{build}
configuration: Release
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: AsmResolver/bin/Release
  name: Latest Build
deploy:
  provider: NuGet
  api_key:
    secure: vZjUvk6GBXzuEgIRaJ6gsbyjLzYVOozBGX0ZycdseqTK2q0XLmJgRAk758ugrzsV
  skip_symbols: false
  artifact: /.*\.nupkg/